spring.application.name=gateway-service
server.port=9090

#spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

# Convert service names to lowercase
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Force registration with IP instead of hostname
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# Cleaner instance ID format
eureka.instance.instance-id=${spring.application.name}:${server.port}

eureka.client.serviceUrl.defaultZone=http://localhost:8080/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.config.enabled=false

jwt.secret=xhQ1nuOIoDzF4d5wGt4Z19gy8Z+86aYh9575YtpIM3bDHn/pelJ8B/KMvFuYN7cQ
spring.main.web-application-type=reactive

## Auth Service
#spring.cloud.gateway.routes[0].id=auth-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8084
#spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
#
## Brief Service
#spring.cloud.gateway.routes[1].id=Brief-Service
#spring.cloud.gateway.routes[1].uri=http://localhost:8081
#spring.cloud.gateway.routes[1].predicates[0]=Path=/brief/**
#spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
#
##Rendu Service
#spring.cloud.gateway.routes[2].id=Rendu-Service
#spring.cloud.gateway.routes[2].uri=http://localhost:8083
#spring.cloud.gateway.routes[2].predicates[0]=Path=/rendu/**
#spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1


